#!/bin/bash
set -e  

# Function to adjust permissions of directories and files
adjust_permissions() {
  local dir=$1
  if [ -d "$dir" ]; then
    echo "Adjusting permissions in: $dir"
    find "$dir" -type d ! -perm 755 -exec chmod 755 {} +
    find "$dir" -type f ! -perm 644 -exec chmod 644 {} +
  else
    echo "Directory $dir does not exist."
  fi
}

# Function to add alias to each user's .bashrc
add_alias_to_bashrc() {
    local bashrc_file="$1/.bashrc"
    local alias_command="alias tahoma2d='tahoma2d; tahoma-permissions'"

    if [ ! -f "$bashrc_file" ]; then
        echo "Creating $bashrc_file..."
        touch "$bashrc_file"
    fi

    if ! grep -qF "$alias_command" "$bashrc_file"; then
        echo "Adding alias to .bashrc in $bashrc_file..."
        echo "$alias_command" >> "$bashrc_file"
    fi
}

# Copy files from /etc/skel and adjust permissions
SRC="/etc/skel/.local/share/Tahoma2D"
if [ ! -d "$SRC" ]; then
  echo "Source directory $SRC does not exist. Aborting."
  exit 1
fi

for user_dir in /home/*; do
  if [ -d "$user_dir" ] && [ -f "$user_dir/.bashrc" ]; then  # Verify if it is a valid user directory
    USER_TAHOMA_DIR="$user_dir/.local/share/Tahoma2D"
    LIBRARY_DIR="$USER_TAHOMA_DIR/tahomastuff/library"

    echo "Processing $USER_TAHOMA_DIR..."

    mkdir -p "$USER_TAHOMA_DIR"
    [ -d "$LIBRARY_DIR" ] && rm -rf "$LIBRARY_DIR"/*
    cp -ru "$SRC/"* "$USER_TAHOMA_DIR/"
    chown -R "$(basename "$user_dir")":"$(basename "$user_dir")" "$USER_TAHOMA_DIR"

    # Add alias to .bashrc
    add_alias_to_bashrc "$user_dir"

    # Adjust permissions
    adjust_permissions "$USER_TAHOMA_DIR"
    for file in AppRun usr/bin/Tahoma2D usr/bin/tahoma2d usr/bin/lzocompress usr/bin/lzodecompress \
                 usr/bin/tcleanup usr/bin/tcomposer usr/bin/tfarmcontroller usr/bin/tconverter \
                 usr/bin/tfarmserver rhubarb/rhubarb ffmpeg/ffprobe; do
        [ -f "$USER_TAHOMA_DIR/$file" ] && chmod +x "$USER_TAHOMA_DIR/$file"
    done
    find "$USER_TAHOMA_DIR/ffmpeg" -type f ! -perm /u+x -exec chmod +x {} +
  else
    echo "Skipping $user_dir: not a valid user directory."
  fi
done

# Adjust common permissions
adjust_permissions "$HOME/.local/share/Tahoma2D/tahomastuff/profiles"
adjust_permissions "$HOME/.local/share/Tahoma2D/tahomastuff/sandbox"
adjust_permissions "$HOME/.local/share/Tahoma2D/tahomastuff/doc"
adjust_permissions "$HOME/.local/share/Tahoma2D/tahomastuff/config"
adjust_permissions "$HOME/.local/share/Tahoma2D/usr/share/doc"
adjust_permissions "$HOME/.cache/Tahoma2D"
adjust_permissions "$HOME/.local/share/Trash"

# Set execution permissions for necessary binaries
chmod +x /usr/local/bin/tahoma-permissions
chmod +x /usr/local/bin/tahoma2d

echo "Postinst successfully completed."
exit 0