#!/bin/bash

DIR="`dirname \"$0\"`" 
DIR="`( cd \"$DIR\" && readlink -f $(pwd) )`"
echo "DIR: $DIR"
export APPDIR=$DIR

export CAMLIBS=`find $APPDIR/../Resources/libgphoto2 -mindepth 1 -type d`
echo "CAMLIBS: $CAMLIBS"

export IOLIBS=`find $APPDIR/../Resources/libgphoto2_port -mindepth 1 -type d`
echo "IOLIBS: $IOLIBS"

exec $APPDIR/Tahoma2D.real "$@"
