[Icon Theme]
Name=light
Comment=a light icon set for use in dark themes

Directories=actions/16,actions/18,actions/22,actions/60,console/22,tools/22,devices/22

[actions/16]
Size=16
Type=Scalable

[actions/18]
Size=18
Type=Scalable

[actions/22]
Size=22
Type=Scalable

[console/22]
Size=22
Type=Scalable

[tools/22]
Size=22
Type=Scalabe

[devices/22]
Size=22
Type=Scalable

[actions/60]
Size=60
Type=Scalable
