#pragma once

#ifndef TOONZTAGS_H
#define TOONZTAGS_H
/*
              TOONZ 4
*/

#define TIFFTAG_TOONZPALETTE 34750
#define TIFFTAG_TOONZCOLORNAMES 34751
#define TIFFTAG_TOONZWINDOW 34752
#define TIFFTAG_TOONZHISTORY 34753

/*
#define FIELD_TOONZPALETTE		60
#define FIELD_TOONZCOLORNAMES		61
#define FIELD_TOONZWINDOW		62
#define FIELD_TOONZHISTORY		63
*/

#define FIELD_TOONZPALETTE FIELD_CUSTOM
#define FIELD_TOONZCOLORNAMES FIELD_CUSTOM
#define FIELD_TOONZWINDOW FIELD_CUSTOM
#define FIELD_TOONZHISTORY FIELD_CUSTOM

#define TOONZPALETTE_COUNT 16 /* Numero dei campi (stiamo larghi) */
#define TOONZWINDOW_COUNT 16  /* Numero dei campi (stiamo larghi) */

#endif
